drop table if exists tasks;

create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(100) not null unique,
    description varchar(500),
    status varchar(20) not null,
    priority varchar(20) not null,
    due_date date,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_tasks_status on tasks(status);
create index idx_tasks_priority on tasks(priority);
create index idx_tasks_due_date on tasks(due_date);
