create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(100) not null unique,
    description varchar(500),
    status varchar(20) not null,
    priority varchar(20) not null,
    due_date date,
    created_at timestamp not null,
    updated_at timestamp not null
);
